apiVersion: v1
entries:
  atto-app:
  - apiVersion: v2
    appVersion: 2.0.8
    created: "2022-06-08T14:00:20.17578+01:00"
    description: A Helm chart for Kubernetes
    digest: b20548e98b9970befdeffb8aebda4a6b00f6afce632add4b6386807262829028
    name: atto-app
    type: application
    urls:
    - https://attopartners.github.io/helmcharts/charts/atto-app-0.2.10.tgz
    version: 0.2.10
  - apiVersion: v2
    appVersion: 2.0.8
    created: "2022-06-08T14:00:20.177162+01:00"
    description: A Helm chart for Kubernetes
    digest: c83294d5df44a2f8101dc79c1b92d477a2d1f90facdbfe4565825e735a4fd124
    name: atto-app
    type: application
    urls:
    - https://attopartners.github.io/helmcharts/charts/atto-app-0.2.9.tgz
    version: 0.2.9
  - apiVersion: v2
    appVersion: 2.0.8
    created: "2022-06-08T14:00:20.176652+01:00"
    description: A Helm chart for Kubernetes
    digest: 468a41c7b4e717511e8ad57202a255b20a8880700fcfa6944ceca94c23b26d91
    name: atto-app
    type: application
    urls:
    - https://attopartners.github.io/helmcharts/charts/atto-app-0.2.8.tgz
    version: 0.2.8
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2022-06-08T14:00:20.175312+01:00"
    description: A Helm chart for Kubernetes
    digest: 8759f26720d6082696c60519c934758f9e61ee59dfad69ee543cc93fa478d3cf
    name: atto-app
    type: application
    urls:
    - https://attopartners.github.io/helmcharts/charts/atto-app-0.1.23.tgz
    version: 0.1.23
generated: "2022-06-08T14:00:20.174726+01:00"
