apiVersion: v1
entries:
  atto-app:
  - apiVersion: v2
    appVersion: 2.0.8
    created: "2022-06-10T11:44:03.214712+01:00"
    description: A Helm chart for Kubernetes
    digest: f048e2b23f9b4f42fa3e2afb6aa6714825b21013630c74848bfba4f9da241390
    name: atto-app
    type: application
    urls:
    - https://attopartners.github.io/helmcharts/charts/atto-app-0.2.12.tgz
    version: 0.2.12
  - apiVersion: v2
    appVersion: 2.0.8
    created: "2022-06-10T11:44:03.21432+01:00"
    description: A Helm chart for Kubernetes
    digest: 5fe95dd1c32224158c7557a501b7fb65c1bb8a5e2f90fea68cb97111b70b2118
    name: atto-app
    type: application
    urls:
    - https://attopartners.github.io/helmcharts/charts/atto-app-0.2.11.tgz
    version: 0.2.11
  - apiVersion: v2
    appVersion: 2.0.8
    created: "2022-06-10T11:44:03.215722+01:00"
    description: A Helm chart for Kubernetes
    digest: 920f9d6c3838ba989052cd16d40aba2f0b19b95ded1a25b1915c5e848f2dbd28
    name: atto-app
    type: application
    urls:
    - https://attopartners.github.io/helmcharts/charts/atto-app-0.2.9.tgz
    version: 0.2.9
  - apiVersion: v2
    appVersion: 2.0.8
    created: "2022-06-10T11:44:03.215168+01:00"
    description: A Helm chart for Kubernetes
    digest: 468a41c7b4e717511e8ad57202a255b20a8880700fcfa6944ceca94c23b26d91
    name: atto-app
    type: application
    urls:
    - https://attopartners.github.io/helmcharts/charts/atto-app-0.2.8.tgz
    version: 0.2.8
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2022-06-10T11:44:03.21367+01:00"
    description: A Helm chart for Kubernetes
    digest: 8759f26720d6082696c60519c934758f9e61ee59dfad69ee543cc93fa478d3cf
    name: atto-app
    type: application
    urls:
    - https://attopartners.github.io/helmcharts/charts/atto-app-0.1.23.tgz
    version: 0.1.23
generated: "2022-06-10T11:44:03.212699+01:00"
