apiVersion: v1
entries:
  atto-app:
  - apiVersion: v2
    appVersion: 2.0.4
    created: "2021-11-15T13:12:38.659537Z"
    description: A Helm chart for Kubernetes
    digest: 7a0672acad4b91cf89cb6330d65634741ad59648bdc3a1788db573539599f946
    name: atto-app
    type: application
    urls:
    - https://attopartners.github.io/helmcharts/charts/atto-app-0.2.4.tgz
    version: 0.2.4
  - apiVersion: v2
    appVersion: 2.0.3
    created: "2021-11-15T13:12:38.659031Z"
    description: A Helm chart for Kubernetes
    digest: 689379df4e278dbeb4f5d8d5490986767c4d4680f24569bcf445d2bf9694b5d4
    name: atto-app
    type: application
    urls:
    - https://attopartners.github.io/helmcharts/charts/atto-app-0.2.3.tgz
    version: 0.2.3
  - apiVersion: v2
    appVersion: 2.0.2
    created: "2021-11-15T13:12:38.658528Z"
    description: A Helm chart for Kubernetes
    digest: e4c8e9bbabd3918e2a3484bae903153c5b5dc80f67f1f76742c9e231d1b97d5d
    name: atto-app
    type: application
    urls:
    - https://attopartners.github.io/helmcharts/charts/atto-app-0.2.2.tgz
    version: 0.2.2
  - apiVersion: v2
    appVersion: 2.0.1
    created: "2021-11-15T13:12:38.657966Z"
    description: A Helm chart for Kubernetes
    digest: 9bb6f6936f8544d1f19ee104d7fa69886d0d2bee0f5201684d4e9dc0dbd886db
    name: atto-app
    type: application
    urls:
    - https://attopartners.github.io/helmcharts/charts/atto-app-0.2.1.tgz
    version: 0.2.1
  - apiVersion: v2
    appVersion: 2.0.0
    created: "2021-11-15T13:12:38.655711Z"
    description: A Helm chart for Kubernetes
    digest: 5200ffcf974b59fe35dadc74010d418ee89af287aead6aee69a8cc72378c79b8
    name: atto-app
    type: application
    urls:
    - https://attopartners.github.io/helmcharts/charts/atto-app-0.2.0.tgz
    version: 0.2.0
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2021-11-15T13:12:38.655244Z"
    description: A Helm chart for Kubernetes
    digest: 8759f26720d6082696c60519c934758f9e61ee59dfad69ee543cc93fa478d3cf
    name: atto-app
    type: application
    urls:
    - https://attopartners.github.io/helmcharts/charts/atto-app-0.1.23.tgz
    version: 0.1.23
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2021-11-15T13:12:38.654738Z"
    description: A Helm chart for Kubernetes
    digest: b783cc6202c092deac39f417430a2d60857e10b405c11892f9ef87e8b00e8e0b
    name: atto-app
    type: application
    urls:
    - https://attopartners.github.io/helmcharts/charts/atto-app-0.1.22.tgz
    version: 0.1.22
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2021-11-15T13:12:38.654277Z"
    description: A Helm chart for Kubernetes
    digest: 72589a164e03de166ed63939e0b63b9215a92cfd3da506fd3d41bd2a0532901c
    name: atto-app
    type: application
    urls:
    - https://attopartners.github.io/helmcharts/charts/atto-app-0.1.21.tgz
    version: 0.1.21
generated: "2021-11-15T13:12:38.653644Z"
