apiVersion: v1
entries:
  atto-app:
  - apiVersion: v2
    appVersion: 2.0.8
    created: "2024-02-08T20:49:48.310116Z"
    description: A Helm chart for Kubernetes
    digest: f0a3e159b33bc54a042a50ae13360c2fd6bc8feb44eae63d264a9eadb4dbd487
    name: atto-app
    type: application
    urls:
    - https://attopartners.github.io/helmcharts/charts/atto-app-0.2.27.tgz
    version: 0.2.27
  - apiVersion: v2
    appVersion: 2.0.8
    created: "2024-02-08T20:49:48.309739Z"
    description: A Helm chart for Kubernetes
    digest: fb87f5cf99398035216f5d6c5cc19f2a85cd296f74d276072d5bc8ee4c0a2ff4
    name: atto-app
    type: application
    urls:
    - https://attopartners.github.io/helmcharts/charts/atto-app-0.2.26.tgz
    version: 0.2.26
  - apiVersion: v2
    appVersion: 2.0.8
    created: "2024-02-08T20:49:48.309378Z"
    description: A Helm chart for Kubernetes
    digest: d6c2cdbfc6498c391a806460948cd388205ff40e3fb1543373042fae4fbc122f
    name: atto-app
    type: application
    urls:
    - https://attopartners.github.io/helmcharts/charts/atto-app-0.2.25.tgz
    version: 0.2.25
  - apiVersion: v2
    appVersion: 2.0.8
    created: "2024-02-08T20:49:48.308712Z"
    description: A Helm chart for Kubernetes
    digest: 8350befefbb5de6524cecc033bfd11efca9c0b5ac0c46ae3dfa3254574bebf83
    name: atto-app
    type: application
    urls:
    - https://attopartners.github.io/helmcharts/charts/atto-app-0.2.24.tgz
    version: 0.2.24
  - apiVersion: v2
    appVersion: 2.0.8
    created: "2024-02-08T20:49:48.307687Z"
    description: A Helm chart for Kubernetes
    digest: aa712dde9a33fdba7a37783d6218ac52a42e8ba2565ee42145d11b4c6cce9141
    name: atto-app
    type: application
    urls:
    - https://attopartners.github.io/helmcharts/charts/atto-app-0.2.23.tgz
    version: 0.2.23
  - apiVersion: v2
    appVersion: 2.0.8
    created: "2024-02-08T20:49:48.30717Z"
    description: A Helm chart for Kubernetes
    digest: 5cb172f748c63f30caa22252bc10d2ac4668706e3fdb771b9c61cd8b85e77bd6
    name: atto-app
    type: application
    urls:
    - https://attopartners.github.io/helmcharts/charts/atto-app-0.2.22.tgz
    version: 0.2.22
  - apiVersion: v2
    appVersion: 2.0.8
    created: "2024-02-08T20:49:48.30666Z"
    description: A Helm chart for Kubernetes
    digest: 7047a0bb8c30022354bb27c3fd3e5c2904308e3559a7b1ebecee946daa6b6762
    name: atto-app
    type: application
    urls:
    - https://attopartners.github.io/helmcharts/charts/atto-app-0.2.21.tgz
    version: 0.2.21
  - apiVersion: v2
    appVersion: 2.0.8
    created: "2024-02-08T20:49:48.306179Z"
    description: A Helm chart for Kubernetes
    digest: f7c3b17c48140c9d2ae11411f8821ee4ed2511fcc2ee550b705b2f5df5dbdec0
    name: atto-app
    type: application
    urls:
    - https://attopartners.github.io/helmcharts/charts/atto-app-0.2.20.tgz
    version: 0.2.20
  - apiVersion: v2
    appVersion: 2.0.8
    created: "2024-02-08T20:49:48.305689Z"
    description: A Helm chart for Kubernetes
    digest: dfd28b152f0a44bc9208e70b38d3f64a6d0662d1bb19c5eaa3f54009be6c50f0
    name: atto-app
    type: application
    urls:
    - https://attopartners.github.io/helmcharts/charts/atto-app-0.2.19.tgz
    version: 0.2.19
  - apiVersion: v2
    appVersion: 2.0.8
    created: "2024-02-08T20:49:48.305204Z"
    description: A Helm chart for Kubernetes
    digest: 12a1f43c473fed3f5b6986d3144dfcec61470bbd03329675ce60d6e8569e06ba
    name: atto-app
    type: application
    urls:
    - https://attopartners.github.io/helmcharts/charts/atto-app-0.2.18.tgz
    version: 0.2.18
  - apiVersion: v2
    appVersion: 2.0.8
    created: "2024-02-08T20:49:48.304677Z"
    description: A Helm chart for Kubernetes
    digest: 3281df511f754b213fb067c6f6b4527295c0f86870fdaaeada20d121c2f72f1e
    name: atto-app
    type: application
    urls:
    - https://attopartners.github.io/helmcharts/charts/atto-app-0.2.17.tgz
    version: 0.2.17
  - apiVersion: v2
    appVersion: 2.0.8
    created: "2024-02-08T20:49:48.304174Z"
    description: A Helm chart for Kubernetes
    digest: b1c10e67a88c099c8b042d8ec781dcb7daa1dfb26a50db79ad1ac4f45edb3b68
    name: atto-app
    type: application
    urls:
    - https://attopartners.github.io/helmcharts/charts/atto-app-0.2.16.tgz
    version: 0.2.16
  - apiVersion: v2
    appVersion: 2.0.8
    created: "2024-02-08T20:49:48.303655Z"
    description: A Helm chart for Kubernetes
    digest: 84c83ce0d61eda874e0cb736ebae50fa2a75c0a71bb2d4cc7e695b6b1881e2bf
    name: atto-app
    type: application
    urls:
    - https://attopartners.github.io/helmcharts/charts/atto-app-0.2.15.tgz
    version: 0.2.15
  - apiVersion: v2
    appVersion: 2.0.8
    created: "2024-02-08T20:49:48.303126Z"
    description: A Helm chart for Kubernetes
    digest: 91db8bad84d9a229af502710bddffe10fdaba03901082e61c9f1b5b262bd628e
    name: atto-app
    type: application
    urls:
    - https://attopartners.github.io/helmcharts/charts/atto-app-0.2.14.tgz
    version: 0.2.14
  - apiVersion: v2
    appVersion: 2.0.8
    created: "2024-02-08T20:49:48.301787Z"
    description: A Helm chart for Kubernetes
    digest: 1283039508b094ea279673b1202ebb68af2b774f94c758d37d87c077906d05f6
    name: atto-app
    type: application
    urls:
    - https://attopartners.github.io/helmcharts/charts/atto-app-0.2.13.tgz
    version: 0.2.13
  - apiVersion: v2
    appVersion: 2.0.8
    created: "2024-02-08T20:49:48.301253Z"
    description: A Helm chart for Kubernetes
    digest: f048e2b23f9b4f42fa3e2afb6aa6714825b21013630c74848bfba4f9da241390
    name: atto-app
    type: application
    urls:
    - https://attopartners.github.io/helmcharts/charts/atto-app-0.2.12.tgz
    version: 0.2.12
  - apiVersion: v2
    appVersion: 2.0.8
    created: "2024-02-08T20:49:48.30072Z"
    description: A Helm chart for Kubernetes
    digest: 5fe95dd1c32224158c7557a501b7fb65c1bb8a5e2f90fea68cb97111b70b2118
    name: atto-app
    type: application
    urls:
    - https://attopartners.github.io/helmcharts/charts/atto-app-0.2.11.tgz
    version: 0.2.11
  - apiVersion: v2
    appVersion: 2.0.8
    created: "2024-02-08T20:49:48.310917Z"
    description: A Helm chart for Kubernetes
    digest: 920f9d6c3838ba989052cd16d40aba2f0b19b95ded1a25b1915c5e848f2dbd28
    name: atto-app
    type: application
    urls:
    - https://attopartners.github.io/helmcharts/charts/atto-app-0.2.9.tgz
    version: 0.2.9
  - apiVersion: v2
    appVersion: 2.0.8
    created: "2024-02-08T20:49:48.310471Z"
    description: A Helm chart for Kubernetes
    digest: 468a41c7b4e717511e8ad57202a255b20a8880700fcfa6944ceca94c23b26d91
    name: atto-app
    type: application
    urls:
    - https://attopartners.github.io/helmcharts/charts/atto-app-0.2.8.tgz
    version: 0.2.8
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2024-02-08T20:49:48.300199Z"
    description: A Helm chart for Kubernetes
    digest: 8759f26720d6082696c60519c934758f9e61ee59dfad69ee543cc93fa478d3cf
    name: atto-app
    type: application
    urls:
    - https://attopartners.github.io/helmcharts/charts/atto-app-0.1.23.tgz
    version: 0.1.23
generated: "2024-02-08T20:49:48.299122Z"
