apiVersion: v1
entries:
  atto-app:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2020-03-09T17:35:38.182422Z"
    description: A Helm chart for Kubernetes
    digest: 11fd754c857a70d97326bcf32e12a65601d159d6d354b3442ae0f36b6f01b315
    name: atto-app
    type: application
    urls:
    - https://attopartners.github.io/helmcharts/charts/atto-app-0.1.15.tgz
    version: 0.1.15
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2020-03-09T17:35:38.181937Z"
    description: A Helm chart for Kubernetes
    digest: 09739fc1be283d94166b6897b5bc521de0374753c9a821d451be36dfe3bf5e12
    name: atto-app
    type: application
    urls:
    - https://attopartners.github.io/helmcharts/charts/atto-app-0.1.14.tgz
    version: 0.1.14
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2020-03-09T17:35:38.181168Z"
    description: A Helm chart for Kubernetes
    digest: 2a77cbdf68c74b89c1d55caddbaa762ff938c3d17820e4a4d7eb78f303362875
    name: atto-app
    type: application
    urls:
    - https://attopartners.github.io/helmcharts/charts/atto-app-0.1.13.tgz
    version: 0.1.13
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2020-03-09T17:35:38.180398Z"
    description: A Helm chart for Kubernetes
    digest: 1b206a3c285b9933c2ee1635ca7f1965b073a2878e8b211d145124072254d631
    name: atto-app
    type: application
    urls:
    - https://attopartners.github.io/helmcharts/charts/atto-app-0.1.12.tgz
    version: 0.1.12
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2020-03-09T17:35:38.178752Z"
    description: A Helm chart for Kubernetes
    digest: 63babaa335396968e3fbe5d308ded115bee6ab90316c034c87b415f49eb55218
    name: atto-app
    type: application
    urls:
    - https://attopartners.github.io/helmcharts/charts/atto-app-0.1.11.tgz
    version: 0.1.11
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2020-03-09T17:35:38.177972Z"
    description: A Helm chart for Kubernetes
    digest: 035691d5fc61a63d481f4ceb9e61fa3fe51aac8930e736c4984642760e1672e6
    name: atto-app
    type: application
    urls:
    - https://attopartners.github.io/helmcharts/charts/atto-app-0.1.10.tgz
    version: 0.1.10
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2020-03-09T17:35:38.190937Z"
    description: A Helm chart for Kubernetes
    digest: 92f5a91ae188963838603f3a16f6ea4a215f077e0b5475adfcfa146260f332b6
    name: atto-app
    type: application
    urls:
    - https://attopartners.github.io/helmcharts/charts/atto-app-0.1.9.tgz
    version: 0.1.9
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2020-03-09T17:35:38.189749Z"
    description: A Helm chart for Kubernetes
    digest: f79e2182812c192661877444b68a23624fee360cc8c6018c4dc70dca320d6f35
    name: atto-app
    type: application
    urls:
    - https://attopartners.github.io/helmcharts/charts/atto-app-0.1.8.tgz
    version: 0.1.8
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2020-03-09T17:35:38.188922Z"
    description: A Helm chart for Kubernetes
    digest: d82dc484376ddbf01ce48615def4812dbc6483ef035c311860e0843af5df4e21
    name: atto-app
    type: application
    urls:
    - https://attopartners.github.io/helmcharts/charts/atto-app-0.1.7.tgz
    version: 0.1.7
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2020-03-09T17:35:38.187963Z"
    description: A Helm chart for Kubernetes
    digest: 089a2d903b2a2f8e21b20e3d7fd7ea8f8ae2e09c15942f18fddb8d4379855268
    name: atto-app
    type: application
    urls:
    - https://attopartners.github.io/helmcharts/charts/atto-app-0.1.6.tgz
    version: 0.1.6
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2020-03-09T17:35:38.186945Z"
    description: A Helm chart for Kubernetes
    digest: 2d59c45bd5808bdeafc0bc0a8ebfd38e6217ab18e97bd50bb59d8db6a56ce9de
    name: atto-app
    type: application
    urls:
    - https://attopartners.github.io/helmcharts/charts/atto-app-0.1.5.tgz
    version: 0.1.5
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2020-03-09T17:35:38.185559Z"
    description: A Helm chart for Kubernetes
    digest: 05da353fb546a5b64918680f944b79bab284d16a52f325811e960a04f9b658d1
    name: atto-app
    type: application
    urls:
    - https://attopartners.github.io/helmcharts/charts/atto-app-0.1.4.tgz
    version: 0.1.4
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2020-03-09T17:35:38.184536Z"
    description: A Helm chart for Kubernetes
    digest: fe7baf0b29ef0feaab9fc0651110d0c20f741d44c0947d3f75d30ea92b2b2b70
    name: atto-app
    type: application
    urls:
    - https://attopartners.github.io/helmcharts/charts/atto-app-0.1.3.tgz
    version: 0.1.3
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2020-03-09T17:35:38.18355Z"
    description: A Helm chart for Kubernetes
    digest: 57d9293dd747956d0fa487510467a3cbc189a47554341a2103727e3179688672
    name: atto-app
    type: application
    urls:
    - https://attopartners.github.io/helmcharts/charts/atto-app-0.1.2.tgz
    version: 0.1.2
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2020-03-09T17:35:38.176196Z"
    description: A Helm chart for Kubernetes
    digest: a6d0d597e45c3c8295fe8f83ff297a028cd4cdf83337d39cd9d72bbcf43b3db3
    name: atto-app
    type: application
    urls:
    - https://attopartners.github.io/helmcharts/charts/atto-app-0.1.1.tgz
    version: 0.1.1
generated: "2020-03-09T17:35:38.170404Z"
