{{- $root := . -}}
{{- range .Values.jobs -}}
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ .name }}
spec:
  schedule: {{ .schedule }}
  jobTemplate:      
    spec:
      template:
        metadata:
          annotations:
            vault.hashicorp.com/agent-requests-cpu: ""
            vault.hashicorp.com/agent-requests-mem: ""
            {{- with $root.Values.vault }}
              {{- toYaml . | nindent 12 -}}
            {{- end }}
            vault.hashicorp.com/agent-pre-populate-only: "true"
            {{- with $root.Values.annotations }}
              {{- toYaml . | nindent 12 -}}
            {{- end }}  
        {{- with $root.Values.imagePullSecrets }}
        imagePullSecrets:
          {{- toYaml . | nindent 8 }}
        {{- end }}
        spec:
          restartPolicy: "Never"
          containers:
            - name: {{ $root.Chart.Name }}
              imagePullPolicy: Always
              image: "{{ $root.Values.image.repository }}:{{ $root.Values.commit }}"
              args: {{ .args }}
---
{{- end -}}