{{- $root := . -}}
{{- $serviceAccountName := include "atto-app.serviceAccountName" . -}}
{{- range .Values.jobs -}}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .name }}
spec:
  schedule: {{ .schedule }}
  jobTemplate:      
    spec:
      template:
        metadata:
          annotations:
            {{- with $root.Values.annotations }}
              {{- toYaml . | nindent 12 -}}
            {{- end }}  
        {{- with $root.Values.imagePullSecrets }}
        imagePullSecrets:
          {{- toYaml . | nindent 8 }}
        {{- end }}
        spec:
          restartPolicy: "Never"
          serviceAccountName: {{ $serviceAccountName  }}
          containers:
            - name: {{ $root.Chart.Name }}
              imagePullPolicy: Always
              image: "{{ $root.Values.image.repository }}:{{ $root.Values.commit }}"
              args:
                {{- with .args }}
                  {{- toYaml . | nindent 16 -}}
                {{- end }}
              env:
                {{- toYaml $root.Values.env | nindent 16 }}
              envFrom:
                {{- toYaml $root.Values.envFrom | nindent 16 }}
---
{{- end -}}