apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "atto-app.fullname" . }}
  labels:
    {{- include "atto-app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      {{- include "atto-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "atto-app.selectorLabels" . | nindent 8 }}
      annotations:
        {{- with .Values.annotations }}
          {{- toYaml . | nindent 8 -}}
        {{- end }}
        
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "atto-app.serviceAccountName" . }}
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app.kubernetes.io/instance
                operator: In
                values:
                - {{ .Release.Name }}
            topologyKey: "kubernetes.io/hostname"
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.commit }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.image.command }}
          command: {{ .Values.image.command }}
          {{- end }}
          {{- if .Values.image.port }}
          ports:
            - name: http
              containerPort: {{ .Values.image.port }}
              protocol: TCP
          readinessProbe:
            httpGet:
              path: {{ .Values.healthcheck }}
              port: http
            initialDelaySeconds: 20
            timeoutSeconds: 5
            failureThreshold: 10
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            {{- toYaml .Values.env | nindent 12 }}
            

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
