{{- if .Values.ingress.enabled -}}
{{- $fullName := include "atto-app.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "atto-app.fullname" . }}
  {{- if eq .Values.ingress.type "cloudflare" }}
  finalizers:
  - strrl.dev/cloudflare-tunnel-ingress-controller-controlled
  {{- end }}
  labels:
    {{- include "atto-app.labels" . | nindent 4 }}
    {{- if eq .Values.ingress.type "nginx" }}
    {{- if eq .Values.ingress.certType "cloudflare" }}
    use-cloudflare-solver: "true"
    {{- else if eq .Values.ingress.certType "http" }}
    use-http-solver: "true"
    {{- end }}
    {{- end }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if eq .Values.ingress.type "cloudflare" }}
  ingressClassName: cloudflare-tunnel
  {{- else }}
  ingressClassName: nginx
  {{- end }}
  {{- if .Values.ingress.spec }}
  {{- with .Values.ingress.spec }}
  {{- toYaml . | nindent 2 }}
  {{- end -}}
  {{ else }}
  {{- if eq .Values.ingress.type "nginx" }}
  tls:
    - hosts:
      {{- range .Values.domains }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ $fullName }}-tls
  {{- end }}
  rules:
  {{- range .Values.domains }}
    - host: {{ . | quote }}
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: {{ $fullName }}
              port: 
                number: {{ $svcPort }}
  {{- end }}
  {{- end }}
{{- end }}