{{- if .Values.migration.enabled -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: migration
  labels:
    {{- include "atto-app.migrationLabels" . | nindent 4 }}
    helm.sh/hook: pre-upgrade
    helm.sh/hook-delete-policy: hook-succeeded
spec:
  template:
    metadata:
      labels:
        {{- include "atto-app.migrationSelectorLabels" . | nindent 8 }}
      annotations:
        {{- with .Values.vault }}
          {{- toYaml . | nindent 8 -}}
        {{- end }}
        {{- with .Values.annotations }}
          {{- toYaml . | nindent 8 -}}
        {{- end }}        
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "atto-app.serviceAccountName" . }}
      restartPolicy: Never
      imagePullPolicy: Always
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.commit }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["bundle", "exec", "rake","db:migrate"]

          resources:
            {{- toYaml .Values.resources | nindent 12 }}
{{- end -}}