{{- if .Values.migration.enabled -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: migration
  labels:
    {{- include "atto-app.migrationLabels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": "pre-upgrade"
    "helm.sh/hook-delete-policy": "hook-succeeded"
    "helm.sh/hook-weight": "-5"
spec:
  backoffLimit: 2
  template:
    metadata:
      labels:
        {{- include "atto-app.migrationSelectorLabels" . | nindent 8 }}
      annotations:
        vault.hashicorp.com/agent-requests-cpu: ""
        vault.hashicorp.com/agent-requests-mem: ""
        {{- with .Values.vault }}
          {{- toYaml . | nindent 8 -}}
        {{- end }}
        vault.hashicorp.com/agent-pre-populate-only: "true"
        {{- with .Values.annotations }}
          {{- toYaml . | nindent 8 -}}
        {{- end }}        
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "atto-app.serviceAccountName" . }}
      restartPolicy: Never
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          image: "{{ .Values.image.repository }}:{{ .Values.commit }}"
          command: ["bundle", "exec", "rake","db:migrate"]

          resources:
            {{- toYaml .Values.resources | nindent 12 }}
{{- end -}}