apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "atto-app.fullname" . }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      {{- include "atto-app.selectorLabels" . | nindent 6 }}