{{- if .Values.shoryuken.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shoryuken
  labels:
    {{- include "atto-app.shoryukenLabels" . | nindent 4 }}      
    {{- with .Values.shoryuken.labels }}
      {{- toYaml . | nindent 4 -}}
    {{- end }} 
spec:
  replicas: {{ .Values.shoryuken.replicaCount }}
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      {{- include "atto-app.shoryukenSelectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "atto-app.shoryukenSelectorLabels" . | nindent 8 }}
      annotations:
        {{- with .Values.annotations }}
          {{- toYaml . | nindent 8 -}}
        {{- end }}       
        {{- with .Values.shoryuken.annotations }}
          {{- toYaml . | nindent 8 -}}
        {{- end }}  
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "atto-app.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.commit }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- if .Values.shoryuken.resources }}
            {{- toYaml .Values.shoryuken.resources | nindent 12 }}
            {{- else }}
            {{- toYaml .Values.resources | nindent 12 }}
            {{- end }}
          env:
            - name: COMMIT
              value: {{ .Values.commit }}
            {{- toYaml .Values.env | nindent 12 }}
          envFrom:
            {{- toYaml .Values.envFrom | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
{{- end -}}